import Link from "next/link";
import "./globals.css";
import { Control } from "./Control";

export const metadata = {
  title: "Web tutorials",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const res = await fetch("http://localhost:9999/topics", {
    // next: { revalidate: 0 },
    // 10초가 지나면 cache가 다시 만들어진다는 의미.

    cache: "no-store",
    // cache를 저장하지 않는다는 의미.
  });
  const topics = await res.json();

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics?.map((topic) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}

        <Control />
      </body>
    </html>
  );
}
